export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const FETCH_EARTHQUAKES = 'FETCH_EARTHQUAKES';
export const RECEIVE_EARTHQUAKES = 'RECEIVE_EARTHQUAKES';
export const FILTER_MAGNITUDE = 'FILTER_MAGNITUDE';
export const FILTER_MAGNITUDE_TYPE = 'FILTER_MAGNITUDE_TYPE';